--- 
- 
  lineinfile: 
    dest: /var/html/www/docova/app/config/parameters.yml
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  name: "Update Docova config file"
  notify: 
  - "restart nginx"
  - "restart php7.1-fpm"
  with_items: 
    - 
      line: "    database_driver: pdo_mysql"
      regexp: "database_driver:"
    - 
      line: "    database_port: 3306"
      regexp: "database_port:"
    - 
      line: "    database_name: {{database_name}}"
      regexp: "database_name:"
    - 
      line: "    database_user: {{database_user}}"
      regexp: "database_user:"
    - 
      line: "    database_password: {{database_password}}"
      regexp: "database_password:"
    - 
      line: "    document_root: {{document_root}}"
      regexp: "document_root:"
- 
  args: 
    chdir: /var/html/www/docova
  become: true
  name: "Running setUpDOCOVA"
  notify: 
    - "restart nginx"
    - "restart php7.1-fpm"
  register: result
  shell: |-
      bash /var/html/www/docova/setUpDOCOVA.sh << EOF
      y
      EOF
- 
  debug: 
    msg: "{{ result.stdout }}"
  name: "Output of setUpDOCOVA"
- 
  become: true
  command: "find /var/html/www/docova  -type d -exec chmod 0755 {} \\;"
  name: "Ensure directories are 0755"
- 
  become: true
  command: "find /var/html/www/docova -type f -exec chmod 0644 {} \\;"
  name: "Ensure files are 0644"
- 
  become: true
  command: "find /var/html/www/docova/var/logs  -type d -exec chmod 0777 {} \\;"
  name: "Ensure files are 0777"
  notify: 
  - "restart nginx"
  - "restart php7.1-fpm"
- 
  name: "Stop Apache which is installed as a dependency of Composer"
  service: 
    name: apache2
    state: stopped
- 
  name: "Disable service httpd, and not touch the state"
  service: 
    enabled: false
    name: apache2
    
- name: Restart service Nginx, in all cases
  service:
    name: nginx
    state: restarted
